// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChXDrA4vfZ_H7JoGorT-H2UBgFPyGLph0',
    appId: '1:1094849858797:web:db53d69fdbb8e8e0f050e4',
    messagingSenderId: '1094849858797',
    projectId: 'pardfifth',
    authDomain: 'pardfifth.firebaseapp.com',
    storageBucket: 'pardfifth.appspot.com',
    measurementId: 'G-YKTK09Q3HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACfCWk8-JJ6MukXN8a4BQJJULTptFxqxo',
    appId: '1:1094849858797:android:b68f12a7d409cd4ff050e4',
    messagingSenderId: '1094849858797',
    projectId: 'pardfifth',
    storageBucket: 'pardfifth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp_wDUzLRuaPLrzPmqZ0ThBGKfmZ6GGI0',
    appId: '1:1094849858797:ios:a962b73bb17b2deef050e4',
    messagingSenderId: '1094849858797',
    projectId: 'pardfifth',
    storageBucket: 'pardfifth.appspot.com',
    iosClientId: '1094849858797-3e4b01rk7rh996bps2s6hjngtoqb63r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp_wDUzLRuaPLrzPmqZ0ThBGKfmZ6GGI0',
    appId: '1:1094849858797:ios:a962b73bb17b2deef050e4',
    messagingSenderId: '1094849858797',
    projectId: 'pardfifth',
    storageBucket: 'pardfifth.appspot.com',
    iosClientId: '1094849858797-3e4b01rk7rh996bps2s6hjngtoqb63r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
